---
- hosts: all
  vars:
    db_user: root
    db_password:
    omeka_db_user: omeka
    omeka_db_password: omeka
    omeka_db_name: omeka
    dev_hostname: omeka-neatline.dev
    omeka_dir: /Users/err8n/omeka/neatlinedev
    omeka_version: stable-2.1
    debug: true
    neatline_repo: git@github.com:scholarslab/Neatline.git
  tasks:
    - include: tasks/install.yaml
    - include: tasks/mysql.yaml
    - include: tasks/apache.yaml
    - include: tasks/omeka.yaml
    - include: tasks/neatline.yaml
    - include: tasks/devtools.yaml
