---
- name: Add {{ dev_hostname }} to /etc/hosts
  lineinfile: >
    dest=/private/etc/hosts
    insertafter=EOF
    line="127.0.0.1    {{ dev_hostname }}"
    state=present
  sudo: yes
- name: Enable mod php5 for Apache
  lineinfile: >
    dest=/private/etc/apache2/httpd.conf
    line="\1"
    regexp="#(LoadModule php5_module libexec/apache2/libphp5\.so)"
    backrefs=yes
    state=present
  sudo: yes
- name: Enable index.php
  lineinfile: >
    dest=/private/etc/apache2/httpd.conf
    line="\1 index.php"
    regexp="^(\s*DirectoryIndex index.html)$"
    backrefs=yes
    state=present
  sudo: yes
- name: AllowOverride All
  script: scripts/allowoverride.py /private/etc/apache2/httpd.conf
  sudo: yes
- name: Enable Virtual Hosts
  lineinfile: >
    dest=/private/etc/apache2/httpd.conf
    line="\1"
    regexp="#(Include /private/etc/apache2/extra/httpd-vhosts.conf)"
    backrefs=yes
    state=present
  sudo: yes
- name: Set up the Virtual Host
  script: scripts/vhost.py /private/etc/apache2/extra/httpd-vhosts.conf {{ dev_hostname }} {{ omeka_dir }}
  sudo: yes
- name: Restart Apache
  shell: apachectl restart
  sudo: yes
